# Generated by Django 4.2.27 on 2025-12-17 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Text prompt for video generation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_url', models.URLField(blank=True, help_text='URL to the generated video', null=True)),
                ('result_file_path', models.CharField(blank=True, help_text='Path to the generated video file', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this generation request', on_delete=django.db.models.deletion.CASCADE, related_name='video_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Generation',
                'verbose_name_plural': 'Video Generations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_videoge_user_id_1cb753_idx')],
            },
        ),
        migrations.CreateModel(
            name='MusicGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_mode', models.BooleanField(default=False, help_text='Enable Custom Mode for advanced audio generation settings')),
                ('instrumental', models.BooleanField(default=False, help_text='Determines if the audio should be instrumental (no lyrics)')),
                ('model', models.CharField(choices=[('V4', 'V4'), ('V4_5', 'V4.5'), ('V4_5PLUS', 'V4.5+'), ('V4_5ALL', 'V4.5 All'), ('V5', 'V5')], default='V4_5ALL', help_text='The model version to use for audio generation', max_length=20)),
                ('prompt', models.TextField(blank=True, help_text='Text prompt for music generation (required in certain modes)', null=True)),
                ('style', models.CharField(blank=True, help_text='The music style or genre for the audio', max_length=1000, null=True)),
                ('title', models.CharField(blank=True, help_text='The title of the generated music track', max_length=100, null=True)),
                ('persona_id', models.CharField(blank=True, help_text='Persona ID to apply to the generated music', max_length=100, null=True)),
                ('negative_tags', models.CharField(blank=True, help_text='Music styles or traits to exclude from the generated audio', max_length=500, null=True)),
                ('vocal_gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], help_text='Preferred vocal gender for generated vocals', max_length=1, null=True)),
                ('style_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the provided style guidance (0.00-1.00)', max_digits=3, null=True)),
                ('weirdness_constraint', models.DecimalField(blank=True, decimal_places=2, help_text='Constraint on creative deviation/novelty (0.00-1.00)', max_digits=3, null=True)),
                ('audio_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the input audio influence (0.00-1.00)', max_digits=3, null=True)),
                ('task_id', models.CharField(blank=True, help_text='Suno API task ID for tracking generation status', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('song_1_url', models.URLField(blank=True, help_text='URL to the first generated song', null=True)),
                ('song_1_stream_url', models.URLField(blank=True, help_text='Stream URL for the first song (available in 30-40 seconds)', null=True)),
                ('song_2_url', models.URLField(blank=True, help_text='URL to the second generated song', null=True)),
                ('song_2_stream_url', models.URLField(blank=True, help_text='Stream URL for the second song (available in 30-40 seconds)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('error_code', models.IntegerField(blank=True, help_text='Error code from Suno API if generation failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this generation request', on_delete=django.db.models.deletion.CASCADE, related_name='music_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Music Generation',
                'verbose_name_plural': 'Music Generations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_musicge_user_id_695d7d_idx'), models.Index(fields=['task_id'], name='api_musicge_task_id_276c62_idx'), models.Index(fields=['status'], name='api_musicge_status_4d8b82_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Text prompt for image generation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_url', models.URLField(blank=True, help_text='URL to the generated image', null=True)),
                ('result_file_path', models.CharField(blank=True, help_text='Path to the generated image file', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this generation request', on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Generation',
                'verbose_name_plural': 'Image Generations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_imagege_user_id_ef0ba0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_chatmes_user_id_5926d3_idx')],
            },
        ),
    ]
