# Generated by Django 4.2.27 on 2026-01-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicgeneration',
            name='song_1_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration of the first song in seconds', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='musicgeneration',
            name='song_1_id',
            field=models.CharField(blank=True, help_text='Suno API unique identifier for the first song', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='musicgeneration',
            name='song_1_image_url',
            field=models.URLField(blank=True, help_text='Cover image URL for the first song', null=True),
        ),
        migrations.AddField(
            model_name='musicgeneration',
            name='song_1_model_name',
            field=models.CharField(blank=True, help_text='Model name used for the first song', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicgeneration',
            name='song_1_tags',
            field=models.CharField(blank=True, help_text='Tags for the first song', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='musicgeneration',
            name='song_2_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration of the second song in seconds', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='musicgeneration',
            name='song_2_id',
            field=models.CharField(blank=True, help_text='Suno API unique identifier for the second song', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='musicgeneration',
            name='song_2_image_url',
            field=models.URLField(blank=True, help_text='Cover image URL for the second song', null=True),
        ),
        migrations.AddField(
            model_name='musicgeneration',
            name='song_2_model_name',
            field=models.CharField(blank=True, help_text='Model name used for the second song', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicgeneration',
            name='song_2_tags',
            field=models.CharField(blank=True, help_text='Tags for the second song', max_length=500, null=True),
        ),
    ]
