# Generated by Django 4.2.27 on 2026-03-07 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_musicgeneration_song_1_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', help_text='Title of the conversation', max_length=255)),
                ('model', models.CharField(default='openai/gpt-4o-mini', help_text='OpenRouter model ID used in this conversation', max_length=100)),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt for this conversation', null=True)),
                ('temperature', models.FloatField(default=0.7, help_text='Sampling temperature (0.0 - 2.0)')),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum tokens in response')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this conversation is archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model',
            field=models.CharField(blank=True, help_text='Model that generated this message (for assistant messages)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tokens_used',
            field=models.IntegerField(blank=True, help_text='Total tokens used for this response', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(help_text='User who owns this message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(help_text='User who owns this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(default=1, help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='api_chatmes_convers_ff7501_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='api_convers_user_id_c08f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_archived'], name='api_convers_user_id_244941_idx'),
        ),
    ]
