# Generated by Django 4.2.27 on 2026-03-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_chatmessage_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text="Exact Model ID from OpenRouter (e.g., 'openai/gpt-4o-mini')", max_length=150, unique=True)),
                ('name', models.CharField(blank=True, help_text="Custom name to display. Leave blank to use OpenRouter's default name", max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available for users to select')),
                ('order', models.IntegerField(default=0, help_text='Display order in the frontend (lower means higher up)')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['order', 'model_id'],
            },
        ),
    ]
