# Generated by Django 4.2.27 on 2026-03-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatmessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this model is selected by default for new chats'),
        ),
    ]
