# Generated by Django 4.2.27 on 2026-04-12 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_aimodel_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый проект', max_length=255)),
                ('type', models.CharField(choices=[('single', 'Single'), ('album', 'Album')], default='single', max_length=10)),
                ('track_count', models.IntegerField(default=1)),
                ('concept', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('suno_prompt', models.TextField(blank=True, null=True)),
                ('suno_style', models.CharField(blank=True, max_length=1000, null=True)),
                ('suno_model', models.CharField(default='V4_5ALL', max_length=20)),
                ('suno_instrumental', models.BooleanField(default=False)),
                ('suno_negative_tags', models.CharField(blank=True, max_length=500, null=True)),
                ('selected_song', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('music_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tracks', to='api.musicgeneration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.project')),
            ],
            options={
                'verbose_name': 'Project Track',
                'verbose_name_plural': 'Project Tracks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.project')),
            ],
            options={
                'verbose_name': 'Project Chat Message',
                'verbose_name_plural': 'Project Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='api_project_user_id_c23708_idx'),
        ),
    ]
